// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

// BanUser provides a mock function with given fields: ctx, adminID, targetUserID
func (_m *AdminService) BanUser(ctx context.Context, adminID int, targetUserID int) error {
	ret := _m.Called(ctx, adminID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, adminID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeUserRole provides a mock function with given fields: ctx, adminID, targetUserID, roleName
func (_m *AdminService) ChangeUserRole(ctx context.Context, adminID int, targetUserID int, roleName string) error {
	ret := _m.Called(ctx, adminID, targetUserID, roleName)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = rf(ctx, adminID, targetUserID, roleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListUsers provides a mock function with given fields: ctx, adminID, limit, offset
func (_m *AdminService) ListUsers(ctx context.Context, adminID int, limit int, offset int) ([]*domain.User, error) {
	ret := _m.Called(ctx, adminID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.User, error)); ok {
		return rf(ctx, adminID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.User); ok {
		r0 = rf(ctx, adminID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, adminID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnbanUser provides a mock function with given fields: ctx, adminID, targetUserID
func (_m *AdminService) UnbanUser(ctx context.Context, adminID int, targetUserID int) error {
	ret := _m.Called(ctx, adminID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, adminID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
