// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommentStatsCache is an autogenerated mock type for the CommentStatsCache type
type CommentStatsCache struct {
	mock.Mock
}

// DecrDislikes provides a mock function with given fields: ctx, commentID
func (_m *CommentStatsCache) DecrDislikes(ctx context.Context, commentID int) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DecrDislikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrLikes provides a mock function with given fields: ctx, commentID
func (_m *CommentStatsCache) DecrLikes(ctx context.Context, commentID int) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DecrLikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStats provides a mock function with given fields: ctx, commentID
func (_m *CommentStatsCache) GetStats(ctx context.Context, commentID int) (int64, int64, bool, error) {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int64
	var r1 int64
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, int64, bool, error)); ok {
		return rf(ctx, commentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) int64); ok {
		r1 = rf(ctx, commentID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) bool); ok {
		r2 = rf(ctx, commentID)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, int) error); ok {
		r3 = rf(ctx, commentID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// IncrDislikes provides a mock function with given fields: ctx, commentID
func (_m *CommentStatsCache) IncrDislikes(ctx context.Context, commentID int) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for IncrDislikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrLikes provides a mock function with given fields: ctx, commentID
func (_m *CommentStatsCache) IncrLikes(ctx context.Context, commentID int) error {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for IncrLikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetStats provides a mock function with given fields: ctx, commentID, likes, dislikes
func (_m *CommentStatsCache) SetStats(ctx context.Context, commentID int, likes int64, dislikes int64) error {
	ret := _m.Called(ctx, commentID, likes, dislikes)

	if len(ret) == 0 {
		panic("no return value specified for SetStats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int64, int64) error); ok {
		r0 = rf(ctx, commentID, likes, dislikes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommentStatsCache creates a new instance of CommentStatsCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentStatsCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentStatsCache {
	mock := &CommentStatsCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
