// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommunityRepository is an autogenerated mock type for the CommunityRepository type
type CommunityRepository struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: ctx, comment
func (_m *CommunityRepository) CreateComment(ctx context.Context, comment *domain.CommunityComment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommunityComment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePost provides a mock function with given fields: ctx, post
func (_m *CommunityRepository) CreatePost(ctx context.Context, post *domain.CommunityPost) error {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommunityPost) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteComment provides a mock function with given fields: ctx, id
func (_m *CommunityRepository) DeleteComment(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePost provides a mock function with given fields: ctx, id
func (_m *CommunityRepository) DeletePost(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCommentByID provides a mock function with given fields: ctx, id
func (_m *CommunityRepository) GetCommentByID(ctx context.Context, id int) (*domain.CommunityComment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *domain.CommunityComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.CommunityComment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.CommunityComment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommunityComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPostByID provides a mock function with given fields: ctx, id
func (_m *CommunityRepository) GetPostByID(ctx context.Context, id int) (*domain.CommunityPost, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPostByID")
	}

	var r0 *domain.CommunityPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.CommunityPost, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.CommunityPost); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommunityPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCommentsByPost provides a mock function with given fields: ctx, postID, limit, offset
func (_m *CommunityRepository) ListCommentsByPost(ctx context.Context, postID int, limit int, offset int) ([]*domain.CommunityComment, error) {
	ret := _m.Called(ctx, postID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListCommentsByPost")
	}

	var r0 []*domain.CommunityComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.CommunityComment, error)); ok {
		return rf(ctx, postID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.CommunityComment); ok {
		r0 = rf(ctx, postID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CommunityComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, postID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPostsByChannel provides a mock function with given fields: ctx, channelID, limit, offset
func (_m *CommunityRepository) ListPostsByChannel(ctx context.Context, channelID int, limit int, offset int) ([]*domain.CommunityPost, error) {
	ret := _m.Called(ctx, channelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListPostsByChannel")
	}

	var r0 []*domain.CommunityPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.CommunityPost, error)); ok {
		return rf(ctx, channelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.CommunityPost); ok {
		r0 = rf(ctx, channelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CommunityPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, channelID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: ctx, comment
func (_m *CommunityRepository) UpdateComment(ctx context.Context, comment *domain.CommunityComment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommunityComment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePost provides a mock function with given fields: ctx, post
func (_m *CommunityRepository) UpdatePost(ctx context.Context, post *domain.CommunityPost) error {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommunityPost) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommunityRepository creates a new instance of CommunityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommunityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommunityRepository {
	mock := &CommunityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
