// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommentService is an autogenerated mock type for the CommentService type
type CommentService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userID, videoID, content
func (_m *CommentService) Create(ctx context.Context, userID int, videoID int, content string) (*domain.Comment, error) {
	ret := _m.Called(ctx, userID, videoID, content)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (*domain.Comment, error)); ok {
		return rf(ctx, userID, videoID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) *domain.Comment); ok {
		r0 = rf(ctx, userID, videoID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, userID, videoID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id, userID, role
func (_m *CommentService) Delete(ctx context.Context, id int, userID int, role string) error {
	ret := _m.Called(ctx, id, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = rf(ctx, id, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CommentService) GetByID(ctx context.Context, id int) (*domain.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCount provides a mock function with given fields: ctx, videoID
func (_m *CommentService) GetCount(ctx context.Context, videoID int) (int64, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByVideo provides a mock function with given fields: ctx, videoID, limit, offset
func (_m *CommentService) ListByVideo(ctx context.Context, videoID int, limit int, offset int) ([]*domain.Comment, error) {
	ret := _m.Called(ctx, videoID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByVideo")
	}

	var r0 []*domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.Comment, error)); ok {
		return rf(ctx, videoID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.Comment); ok {
		r0 = rf(ctx, videoID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, videoID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, userID, content
func (_m *CommentService) Update(ctx context.Context, id int, userID int, content string) (*domain.Comment, error) {
	ret := _m.Called(ctx, id, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (*domain.Comment, error)); ok {
		return rf(ctx, id, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) *domain.Comment); ok {
		r0 = rf(ctx, id, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, id, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentService creates a new instance of CommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentService {
	mock := &CommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
