// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PlaylistRepository is an autogenerated mock type for the PlaylistRepository type
type PlaylistRepository struct {
	mock.Mock
}

// AddVideo provides a mock function with given fields: ctx, playlistID, videoID
func (_m *PlaylistRepository) AddVideo(ctx context.Context, playlistID int, videoID int) error {
	ret := _m.Called(ctx, playlistID, videoID)

	if len(ret) == 0 {
		panic("no return value specified for AddVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, playlistID, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, playlist
func (_m *PlaylistRepository) Create(ctx context.Context, playlist *domain.Playlist) error {
	ret := _m.Called(ctx, playlist)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Playlist) error); ok {
		r0 = rf(ctx, playlist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistRepository) Delete(ctx context.Context, playlistID int) error {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistRepository) GetByID(ctx context.Context, playlistID int) (*domain.Playlist, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Playlist, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Playlist); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetItemsCount provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistRepository) GetItemsCount(ctx context.Context, playlistID int) (int, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetItemsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, playlistID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByChannel provides a mock function with given fields: ctx, channelID, limit, offset
func (_m *PlaylistRepository) ListByChannel(ctx context.Context, channelID int, limit int, offset int) ([]*domain.Playlist, error) {
	ret := _m.Called(ctx, channelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByChannel")
	}

	var r0 []*domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.Playlist, error)); ok {
		return rf(ctx, channelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.Playlist); ok {
		r0 = rf(ctx, channelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, channelID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListItems provides a mock function with given fields: ctx, playlistID, limit, offset
func (_m *PlaylistRepository) ListItems(ctx context.Context, playlistID int, limit int, offset int) ([]*domain.PlaylistItem, error) {
	ret := _m.Called(ctx, playlistID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []*domain.PlaylistItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.PlaylistItem, error)); ok {
		return rf(ctx, playlistID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.PlaylistItem); ok {
		r0 = rf(ctx, playlistID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PlaylistItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, playlistID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveVideo provides a mock function with given fields: ctx, playlistID, videoID
func (_m *PlaylistRepository) RemoveVideo(ctx context.Context, playlistID int, videoID int) error {
	ret := _m.Called(ctx, playlistID, videoID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, playlistID, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, playlist
func (_m *PlaylistRepository) Update(ctx context.Context, playlist *domain.Playlist) error {
	ret := _m.Called(ctx, playlist)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Playlist) error); ok {
		r0 = rf(ctx, playlist)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVideoPosition provides a mock function with given fields: ctx, playlistID, videoID, newPosition
func (_m *PlaylistRepository) UpdateVideoPosition(ctx context.Context, playlistID int, videoID int, newPosition int) error {
	ret := _m.Called(ctx, playlistID, videoID, newPosition)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVideoPosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, playlistID, videoID, newPosition)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPlaylistRepository creates a new instance of PlaylistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistRepository {
	mock := &PlaylistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
