// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RefreshSessionRepository is an autogenerated mock type for the RefreshSessionRepository type
type RefreshSessionRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, tokenID
func (_m *RefreshSessionRepository) Delete(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserID provides a mock function with given fields: ctx, tokenID
func (_m *RefreshSessionRepository) GetUserID(ctx context.Context, tokenID string) (int, bool, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, bool, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, tokenID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Rotate provides a mock function with given fields: ctx, oldTokenID, newTokenID, userID, expiresAt
func (_m *RefreshSessionRepository) Rotate(ctx context.Context, oldTokenID string, newTokenID string, userID int, expiresAt time.Time) (bool, error) {
	ret := _m.Called(ctx, oldTokenID, newTokenID, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Time) (bool, error)); ok {
		return rf(ctx, oldTokenID, newTokenID, userID, expiresAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Time) bool); ok {
		r0 = rf(ctx, oldTokenID, newTokenID, userID, expiresAt)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, time.Time) error); ok {
		r1 = rf(ctx, oldTokenID, newTokenID, userID, expiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, tokenID, userID, expiresAt
func (_m *RefreshSessionRepository) Save(ctx context.Context, tokenID string, userID int, expiresAt time.Time) error {
	ret := _m.Called(ctx, tokenID, userID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Time) error); ok {
		r0 = rf(ctx, tokenID, userID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefreshSessionRepository creates a new instance of RefreshSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshSessionRepository {
	mock := &RefreshSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
