// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

// GetSubscribersCount provides a mock function with given fields: ctx, channelID
func (_m *SubscriptionRepository) GetSubscribersCount(ctx context.Context, channelID int) (int, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscribersCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSubscriptions provides a mock function with given fields: ctx, userID, limit, offset
func (_m *SubscriptionRepository) GetUserSubscriptions(ctx context.Context, userID int, limit int, offset int) ([]*domain.Subscription, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSubscriptions")
	}

	var r0 []*domain.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.Subscription, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.Subscription); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsSubscribed provides a mock function with given fields: ctx, userID, channelID
func (_m *SubscriptionRepository) IsSubscribed(ctx context.Context, userID int, channelID int) (bool, error) {
	ret := _m.Called(ctx, userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for IsSubscribed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return rf(ctx, userID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, userID, channelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotifySubscribersAboutNewVideo provides a mock function with given fields: ctx, channelID
func (_m *SubscriptionRepository) NotifySubscribersAboutNewVideo(ctx context.Context, channelID int) error {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for NotifySubscribersAboutNewVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetNewVideosCount provides a mock function with given fields: ctx, userID, channelID
func (_m *SubscriptionRepository) ResetNewVideosCount(ctx context.Context, userID int, channelID int) error {
	ret := _m.Called(ctx, userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ResetNewVideosCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, userID, channelID
func (_m *SubscriptionRepository) Subscribe(ctx context.Context, userID int, channelID int) (bool, error) {
	ret := _m.Called(ctx, userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return rf(ctx, userID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, userID, channelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unsubscribe provides a mock function with given fields: ctx, userID, channelID
func (_m *SubscriptionRepository) Unsubscribe(ctx context.Context, userID int, channelID int) (bool, error) {
	ret := _m.Called(ctx, userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return rf(ctx, userID, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, userID, channelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSubscriptionRepository creates a new instance of SubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionRepository {
	mock := &SubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
