// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserValidatorService is an autogenerated mock type for the UserValidatorService type
type UserValidatorService struct {
	mock.Mock
}

// ValidateNewUser provides a mock function with given fields: ctx, email, nickname, password
func (_m *UserValidatorService) ValidateNewUser(ctx context.Context, email string, nickname string, password string) error {
	ret := _m.Called(ctx, email, nickname, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNewUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, nickname, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserValidatorService creates a new instance of UserValidatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserValidatorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserValidatorService {
	mock := &UserValidatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
