// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VideoInteractionService is an autogenerated mock type for the VideoInteractionService type
type VideoInteractionService struct {
	mock.Mock
}

// GetStats provides a mock function with given fields: ctx, videoID
func (_m *VideoInteractionService) GetStats(ctx context.Context, videoID int) (*domain.VideoStats, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.VideoStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.VideoStats, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.VideoStats); ok {
		r0 = rf(ctx, videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VideoStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatsBatch provides a mock function with given fields: ctx, videoIDs
func (_m *VideoInteractionService) GetStatsBatch(ctx context.Context, videoIDs []int) (map[int]*domain.VideoStats, error) {
	ret := _m.Called(ctx, videoIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsBatch")
	}

	var r0 map[int]*domain.VideoStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) (map[int]*domain.VideoStats, error)); ok {
		return rf(ctx, videoIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) map[int]*domain.VideoStats); ok {
		r0 = rf(ctx, videoIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]*domain.VideoStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, videoIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rate provides a mock function with given fields: ctx, userID, videoID, action
func (_m *VideoInteractionService) Rate(ctx context.Context, userID int, videoID int, action domain.RatingAction) error {
	ret := _m.Called(ctx, userID, videoID, action)

	if len(ret) == 0 {
		panic("no return value specified for Rate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.RatingAction) error); ok {
		r0 = rf(ctx, userID, videoID, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RecordView provides a mock function with given fields: ctx, userID, videoID
func (_m *VideoInteractionService) RecordView(ctx context.Context, userID int, videoID int) error {
	ret := _m.Called(ctx, userID, videoID)

	if len(ret) == 0 {
		panic("no return value specified for RecordView")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVideoInteractionService creates a new instance of VideoInteractionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoInteractionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoInteractionService {
	mock := &VideoInteractionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
