// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VideoService is an autogenerated mock type for the VideoService type
type VideoService struct {
	mock.Mock
}

// ConfirmUpload provides a mock function with given fields: ctx, videoID, userID
func (_m *VideoService) ConfirmUpload(ctx context.Context, videoID int, userID int) error {
	ret := _m.Called(ctx, videoID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, videoID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteVideo provides a mock function with given fields: ctx, videoID, userID, role
func (_m *VideoService) DeleteVideo(ctx context.Context, videoID int, userID int, role string) error {
	ret := _m.Called(ctx, videoID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) error); ok {
		r0 = rf(ctx, videoID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStreamingPresignedURL provides a mock function with given fields: ctx, videoID
func (_m *VideoService) GetStreamingPresignedURL(ctx context.Context, videoID int) (string, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetStreamingPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVideo provides a mock function with given fields: ctx, videoID
func (_m *VideoService) GetVideo(ctx context.Context, videoID int) (*domain.Video, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetVideo")
	}

	var r0 *domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Video, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Video); ok {
		r0 = rf(ctx, videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitUpload provides a mock function with given fields: ctx, channelID, userID, title, description, filename
func (_m *VideoService) InitUpload(ctx context.Context, channelID int, userID int, title string, description string, filename string) (*domain.Video, string, error) {
	ret := _m.Called(ctx, channelID, userID, title, description, filename)

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 *domain.Video
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) (*domain.Video, string, error)); ok {
		return rf(ctx, channelID, userID, title, description, filename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) *domain.Video); ok {
		r0 = rf(ctx, channelID, userID, title, description, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string) string); ok {
		r1 = rf(ctx, channelID, userID, title, description, filename)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string) error); ok {
		r2 = rf(ctx, channelID, userID, title, description, filename)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListAllVideos provides a mock function with given fields: ctx, limit, offset
func (_m *VideoService) ListAllVideos(ctx context.Context, limit int, offset int) ([]*domain.Video, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListAllVideos")
	}

	var r0 []*domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Video, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Video); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListChannelVideos provides a mock function with given fields: ctx, channelID, limit, offset
func (_m *VideoService) ListChannelVideos(ctx context.Context, channelID int, limit int, offset int) ([]*domain.Video, error) {
	ret := _m.Called(ctx, channelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListChannelVideos")
	}

	var r0 []*domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.Video, error)); ok {
		return rf(ctx, channelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.Video); ok {
		r0 = rf(ctx, channelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, channelID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMyVideos provides a mock function with given fields: ctx, userID, limit, offset
func (_m *VideoService) ListMyVideos(ctx context.Context, userID int, limit int, offset int) ([]*domain.Video, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListMyVideos")
	}

	var r0 []*domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.Video, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.Video); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateVideo provides a mock function with given fields: ctx, videoID, userID, title, description
func (_m *VideoService) UpdateVideo(ctx context.Context, videoID int, userID int, title *string, description *string) (*domain.Video, error) {
	ret := _m.Called(ctx, videoID, userID, title, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVideo")
	}

	var r0 *domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *string) (*domain.Video, error)); ok {
		return rf(ctx, videoID, userID, title, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *string) *domain.Video); ok {
		r0 = rf(ctx, videoID, userID, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *string, *string) error); ok {
		r1 = rf(ctx, videoID, userID, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVideoService creates a new instance of VideoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoService {
	mock := &VideoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
