// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ViewingRepository is an autogenerated mock type for the ViewingRepository type
type ViewingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, viewing
func (_m *ViewingRepository) Create(ctx context.Context, viewing *domain.Viewing) error {
	ret := _m.Called(ctx, viewing)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Viewing) error); ok {
		r0 = rf(ctx, viewing)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTotalViews provides a mock function with given fields: ctx, videoID
func (_m *ViewingRepository) GetTotalViews(ctx context.Context, videoID int) (int, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalViews")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewViewingRepository creates a new instance of ViewingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewViewingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ViewingRepository {
	mock := &ViewingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
