version: '3.8'
services:
  postgres:
    container_name: videohost-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: videohost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: videohost_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data


volumes:
  minio_data:
    name: videohost_minio_data
  postgres_data:
    name: videohost_postgres_data