// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ChannelService is an autogenerated mock type for the ChannelService type
type ChannelService struct {
	mock.Mock
}

// CreateChannel provides a mock function with given fields: ctx, userID, name, description
func (_m *ChannelService) CreateChannel(ctx context.Context, userID int, name string, description string) (*domain.Channel, error) {
	ret := _m.Called(ctx, userID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 *domain.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) (*domain.Channel, error)); ok {
		return rf(ctx, userID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string, string) *domain.Channel); ok {
		r0 = rf(ctx, userID, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string, string) error); ok {
		r1 = rf(ctx, userID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteChannel provides a mock function with given fields: ctx, channelID, userID
func (_m *ChannelService) DeleteChannel(ctx context.Context, channelID int, userID int) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, channelID
func (_m *ChannelService) Exists(ctx context.Context, channelID int) (bool, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannel provides a mock function with given fields: ctx, id
func (_m *ChannelService) GetChannel(ctx context.Context, id int) (*domain.Channel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 *domain.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Channel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Channel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannelByName provides a mock function with given fields: ctx, name
func (_m *ChannelService) GetChannelByName(ctx context.Context, name string) (*domain.Channel, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelByName")
	}

	var r0 *domain.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Channel, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Channel); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChannelByUserID provides a mock function with given fields: ctx, userID
func (_m *ChannelService) GetChannelByUserID(ctx context.Context, userID int) (*domain.Channel, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelByUserID")
	}

	var r0 *domain.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Channel, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Channel); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsOwner provides a mock function with given fields: ctx, channelID, userID
func (_m *ChannelService) IsOwner(ctx context.Context, channelID int, userID int) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateChannel provides a mock function with given fields: ctx, channelID, userID, name, description
func (_m *ChannelService) UpdateChannel(ctx context.Context, channelID int, userID int, name *string, description *string) (*domain.Channel, error) {
	ret := _m.Called(ctx, channelID, userID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateChannel")
	}

	var r0 *domain.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *string) (*domain.Channel, error)); ok {
		return rf(ctx, channelID, userID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *string) *domain.Channel); ok {
		r0 = rf(ctx, channelID, userID, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *string, *string) error); ok {
		r1 = rf(ctx, channelID, userID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewChannelService creates a new instance of ChannelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelService {
	mock := &ChannelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
