// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// channelVideoFilepathRepository is an autogenerated mock type for the channelVideoFilepathRepository type
type channelVideoFilepathRepository struct {
	mock.Mock
}

// ListFilepathsByChannel provides a mock function with given fields: ctx, channelID
func (_m *channelVideoFilepathRepository) ListFilepathsByChannel(ctx context.Context, channelID int) ([]string, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListFilepathsByChannel")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newChannelVideoFilepathRepository creates a new instance of channelVideoFilepathRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newChannelVideoFilepathRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *channelVideoFilepathRepository {
	mock := &channelVideoFilepathRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
