// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommentInteractionService is an autogenerated mock type for the CommentInteractionService type
type CommentInteractionService struct {
	mock.Mock
}

// Dislike provides a mock function with given fields: ctx, userID, commentID
func (_m *CommentInteractionService) Dislike(ctx context.Context, userID int, commentID int) error {
	ret := _m.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for Dislike")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStats provides a mock function with given fields: ctx, commentID
func (_m *CommentInteractionService) GetStats(ctx context.Context, commentID int) (int64, int64, error) {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, int64, error)); ok {
		return rf(ctx, commentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) int64); ok {
		r1 = rf(ctx, commentID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, commentID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Like provides a mock function with given fields: ctx, userID, commentID
func (_m *CommentInteractionService) Like(ctx context.Context, userID int, commentID int) error {
	ret := _m.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for Like")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveRating provides a mock function with given fields: ctx, userID, commentID
func (_m *CommentInteractionService) RemoveRating(ctx context.Context, userID int, commentID int) error {
	ret := _m.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRating")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommentInteractionService creates a new instance of CommentInteractionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentInteractionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentInteractionService {
	mock := &CommentInteractionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
