// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommentRatingRepository is an autogenerated mock type for the CommentRatingRepository type
type CommentRatingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, rating
func (_m *CommentRatingRepository) Create(ctx context.Context, rating *domain.CommentRating) error {
	ret := _m.Called(ctx, rating)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommentRating) error); ok {
		r0 = rf(ctx, rating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, userID, commentID
func (_m *CommentRatingRepository) Delete(ctx context.Context, userID int, commentID int) error {
	ret := _m.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, commentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserAndComment provides a mock function with given fields: ctx, userID, commentID
func (_m *CommentRatingRepository) GetByUserAndComment(ctx context.Context, userID int, commentID int) (*domain.CommentRating, error) {
	ret := _m.Called(ctx, userID, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndComment")
	}

	var r0 *domain.CommentRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.CommentRating, error)); ok {
		return rf(ctx, userID, commentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.CommentRating); ok {
		r0 = rf(ctx, userID, commentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommentRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, commentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with given fields: ctx, commentID
func (_m *CommentRatingRepository) GetStats(ctx context.Context, commentID int) (int64, int64, error) {
	ret := _m.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int64
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, int64, error)); ok {
		return rf(ctx, commentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, commentID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) int64); ok {
		r1 = rf(ctx, commentID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, commentID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, rating
func (_m *CommentRatingRepository) Update(ctx context.Context, rating *domain.CommentRating) error {
	ret := _m.Called(ctx, rating)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CommentRating) error); ok {
		r0 = rf(ctx, rating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommentRatingRepository creates a new instance of CommentRatingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRatingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRatingRepository {
	mock := &CommentRatingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
