// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommunityService is an autogenerated mock type for the CommunityService type
type CommunityService struct {
	mock.Mock
}

// CreateComment provides a mock function with given fields: ctx, postID, userID, content
func (_m *CommunityService) CreateComment(ctx context.Context, postID int, userID int, content string) (*domain.CommunityComment, error) {
	ret := _m.Called(ctx, postID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 *domain.CommunityComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (*domain.CommunityComment, error)); ok {
		return rf(ctx, postID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) *domain.CommunityComment); ok {
		r0 = rf(ctx, postID, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommunityComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, postID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePost provides a mock function with given fields: ctx, channelID, userID, content
func (_m *CommunityService) CreatePost(ctx context.Context, channelID int, userID int, content string) (*domain.CommunityPost, error) {
	ret := _m.Called(ctx, channelID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *domain.CommunityPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (*domain.CommunityPost, error)); ok {
		return rf(ctx, channelID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) *domain.CommunityPost); ok {
		r0 = rf(ctx, channelID, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommunityPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, channelID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteComment provides a mock function with given fields: ctx, commentID, userID
func (_m *CommunityService) DeleteComment(ctx context.Context, commentID int, userID int) error {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePost provides a mock function with given fields: ctx, postID, userID
func (_m *CommunityService) DeletePost(ctx context.Context, postID int, userID int) error {
	ret := _m.Called(ctx, postID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, postID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChannelCommunity provides a mock function with given fields: ctx, channelID
func (_m *CommunityService) GetChannelCommunity(ctx context.Context, channelID int) (*domain.Community, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelCommunity")
	}

	var r0 *domain.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Community, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Community); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMyCommunity provides a mock function with given fields: ctx, userID
func (_m *CommunityService) GetMyCommunity(ctx context.Context, userID int) (*domain.Community, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMyCommunity")
	}

	var r0 *domain.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Community, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Community); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: ctx, commentID, userID, content
func (_m *CommunityService) UpdateComment(ctx context.Context, commentID int, userID int, content string) (*domain.CommunityComment, error) {
	ret := _m.Called(ctx, commentID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 *domain.CommunityComment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (*domain.CommunityComment, error)); ok {
		return rf(ctx, commentID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) *domain.CommunityComment); ok {
		r0 = rf(ctx, commentID, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommunityComment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, commentID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePost provides a mock function with given fields: ctx, postID, userID, content
func (_m *CommunityService) UpdatePost(ctx context.Context, postID int, userID int, content string) (*domain.CommunityPost, error) {
	ret := _m.Called(ctx, postID, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 *domain.CommunityPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) (*domain.CommunityPost, error)); ok {
		return rf(ctx, postID, userID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) *domain.CommunityPost); ok {
		r0 = rf(ctx, postID, userID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommunityPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) error); ok {
		r1 = rf(ctx, postID, userID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommunityService creates a new instance of CommunityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommunityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommunityService {
	mock := &CommunityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
