// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PlaylistService is an autogenerated mock type for the PlaylistService type
type PlaylistService struct {
	mock.Mock
}

// AddVideo provides a mock function with given fields: ctx, playlistID, videoID, userID
func (_m *PlaylistService) AddVideo(ctx context.Context, playlistID int, videoID int, userID int) error {
	ret := _m.Called(ctx, playlistID, videoID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, playlistID, videoID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, channelID, userID, name, description
func (_m *PlaylistService) Create(ctx context.Context, channelID int, userID int, name string, description string) (*domain.Playlist, error) {
	ret := _m.Called(ctx, channelID, userID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) (*domain.Playlist, error)); ok {
		return rf(ctx, channelID, userID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) *domain.Playlist); ok {
		r0 = rf(ctx, channelID, userID, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
		r1 = rf(ctx, channelID, userID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, playlistID, userID
func (_m *PlaylistService) Delete(ctx context.Context, playlistID int, userID int) error {
	ret := _m.Called(ctx, playlistID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, playlistID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, playlistID
func (_m *PlaylistService) GetByID(ctx context.Context, playlistID int) (*domain.Playlist, error) {
	ret := _m.Called(ctx, playlistID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Playlist, error)); ok {
		return rf(ctx, playlistID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Playlist); ok {
		r0 = rf(ctx, playlistID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, playlistID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByChannel provides a mock function with given fields: ctx, channelID, limit, offset
func (_m *PlaylistService) ListByChannel(ctx context.Context, channelID int, limit int, offset int) ([]*domain.Playlist, error) {
	ret := _m.Called(ctx, channelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByChannel")
	}

	var r0 []*domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) ([]*domain.Playlist, error)); ok {
		return rf(ctx, channelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) []*domain.Playlist); ok {
		r0 = rf(ctx, channelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int) error); ok {
		r1 = rf(ctx, channelID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveVideo provides a mock function with given fields: ctx, playlistID, videoID, userID
func (_m *PlaylistService) RemoveVideo(ctx context.Context, playlistID int, videoID int, userID int) error {
	ret := _m.Called(ctx, playlistID, videoID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVideo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int) error); ok {
		r0 = rf(ctx, playlistID, videoID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, playlistID, userID, name, description
func (_m *PlaylistService) Update(ctx context.Context, playlistID int, userID int, name *string, description *string) (*domain.Playlist, error) {
	ret := _m.Called(ctx, playlistID, userID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Playlist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *string) (*domain.Playlist, error)); ok {
		return rf(ctx, playlistID, userID, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *string, *string) *domain.Playlist); ok {
		r0 = rf(ctx, playlistID, userID, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Playlist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *string, *string) error); ok {
		r1 = rf(ctx, playlistID, userID, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPlaylistService creates a new instance of PlaylistService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlaylistService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlaylistService {
	mock := &PlaylistService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
