// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

// DeleteObject provides a mock function with given fields: ctx, key
func (_m *StorageService) DeleteObject(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateAccessPresignedURL provides a mock function with given fields: ctx, key, expiry
func (_m *StorageService) GenerateAccessPresignedURL(ctx context.Context, key string, expiry time.Duration) (string, error) {
	ret := _m.Called(ctx, key, expiry)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateUploadPresignedURL provides a mock function with given fields: ctx, key, expiry
func (_m *StorageService) GenerateUploadPresignedURL(ctx context.Context, key string, expiry time.Duration) (string, error) {
	ret := _m.Called(ctx, key, expiry)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUploadPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, expiry)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
