// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SubscriberCounter is an autogenerated mock type for the SubscriberCounter type
type SubscriberCounter struct {
	mock.Mock
}

// Decrement provides a mock function with given fields: ctx, channelID
func (_m *SubscriberCounter) Decrement(ctx context.Context, channelID int) error {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, channelID
func (_m *SubscriberCounter) Get(ctx context.Context, channelID int) (int, bool, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 int
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, bool, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, channelID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Increment provides a mock function with given fields: ctx, channelID
func (_m *SubscriberCounter) Increment(ctx context.Context, channelID int) error {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadAll provides a mock function with given fields: ctx
func (_m *SubscriberCounter) LoadAll(ctx context.Context) (map[int]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 map[int]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[int]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[int]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, channelID, count
func (_m *SubscriberCounter) Set(ctx context.Context, channelID int, count int) error {
	ret := _m.Called(ctx, channelID, count)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, channelID, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubscriberCounter creates a new instance of SubscriberCounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberCounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberCounter {
	mock := &SubscriberCounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
