// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VideoStatsCache is an autogenerated mock type for the VideoStatsCache type
type VideoStatsCache struct {
	mock.Mock
}

// DecrComments provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) DecrComments(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for DecrComments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrDislikes provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) DecrDislikes(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for DecrDislikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecrLikes provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) DecrLikes(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for DecrLikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCommentsCount provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) GetCommentsCount(ctx context.Context, videoID int) (int64, bool, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentsCount")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, bool, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, videoID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStats provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) GetStats(ctx context.Context, videoID int) (*domain.VideoStats, bool, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *domain.VideoStats
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.VideoStats, bool, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.VideoStats); ok {
		r0 = rf(ctx, videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VideoStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) bool); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, videoID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IncrComments provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) IncrComments(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for IncrComments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrDislikes provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) IncrDislikes(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for IncrDislikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrLikes provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) IncrLikes(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for IncrLikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IncrViews provides a mock function with given fields: ctx, videoID
func (_m *VideoStatsCache) IncrViews(ctx context.Context, videoID int) error {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for IncrViews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadAll provides a mock function with given fields: ctx
func (_m *VideoStatsCache) LoadAll(ctx context.Context) (map[int]domain.VideoStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 map[int]domain.VideoStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[int]domain.VideoStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[int]domain.VideoStats); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]domain.VideoStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCommentsCount provides a mock function with given fields: ctx, videoID, count
func (_m *VideoStatsCache) SetCommentsCount(ctx context.Context, videoID int, count int64) error {
	ret := _m.Called(ctx, videoID, count)

	if len(ret) == 0 {
		panic("no return value specified for SetCommentsCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int64) error); ok {
		r0 = rf(ctx, videoID, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetStats provides a mock function with given fields: ctx, videoID, stats
func (_m *VideoStatsCache) SetStats(ctx context.Context, videoID int, stats *domain.VideoStats) error {
	ret := _m.Called(ctx, videoID, stats)

	if len(ret) == 0 {
		panic("no return value specified for SetStats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *domain.VideoStats) error); ok {
		r0 = rf(ctx, videoID, stats)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVideoStatsCache creates a new instance of VideoStatsCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoStatsCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoStatsCache {
	mock := &VideoStatsCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
