// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VideoRatingRepository is an autogenerated mock type for the VideoRatingRepository type
type VideoRatingRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, rating
func (_m *VideoRatingRepository) Create(ctx context.Context, rating *domain.VideoRating) error {
	ret := _m.Called(ctx, rating)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VideoRating) error); ok {
		r0 = rf(ctx, rating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, userID, videoID
func (_m *VideoRatingRepository) Delete(ctx context.Context, userID int, videoID int) error {
	ret := _m.Called(ctx, userID, videoID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, userID, videoID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserAndVideo provides a mock function with given fields: ctx, userID, videoID
func (_m *VideoRatingRepository) GetByUserAndVideo(ctx context.Context, userID int, videoID int) (*domain.VideoRating, error) {
	ret := _m.Called(ctx, userID, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndVideo")
	}

	var r0 *domain.VideoRating
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*domain.VideoRating, error)); ok {
		return rf(ctx, userID, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *domain.VideoRating); ok {
		r0 = rf(ctx, userID, videoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.VideoRating)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userID, videoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with given fields: ctx, videoID
func (_m *VideoRatingRepository) GetStats(ctx context.Context, videoID int) (int, int, error) {
	ret := _m.Called(ctx, videoID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, int, error)); ok {
		return rf(ctx, videoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, videoID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) int); ok {
		r1 = rf(ctx, videoID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, videoID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, rating
func (_m *VideoRatingRepository) Update(ctx context.Context, rating *domain.VideoRating) error {
	ret := _m.Called(ctx, rating)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.VideoRating) error); ok {
		r0 = rf(ctx, rating)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVideoRatingRepository creates a new instance of VideoRatingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoRatingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoRatingRepository {
	mock := &VideoRatingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
