// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "ZVideo/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VideoRepository is an autogenerated mock type for the VideoRepository type
type VideoRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, video
func (_m *VideoRepository) Create(ctx context.Context, video *domain.Video) error {
	ret := _m.Called(ctx, video)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Video) error); ok {
		r0 = rf(ctx, video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VideoRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *VideoRepository) GetByID(ctx context.Context, id int) (*domain.Video, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Video, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Video); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, limit, offset, sort
func (_m *VideoRepository) List(ctx context.Context, limit int, offset int, sort domain.VideoSort) ([]*domain.Video, error) {
	ret := _m.Called(ctx, limit, offset, sort)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.VideoSort) ([]*domain.Video, error)); ok {
		return rf(ctx, limit, offset, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, domain.VideoSort) []*domain.Video); ok {
		r0 = rf(ctx, limit, offset, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, domain.VideoSort) error); ok {
		r1 = rf(ctx, limit, offset, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByChannel provides a mock function with given fields: ctx, channelID, limit, offset, sort
func (_m *VideoRepository) ListByChannel(ctx context.Context, channelID int, limit int, offset int, sort domain.VideoSort) ([]*domain.Video, error) {
	ret := _m.Called(ctx, channelID, limit, offset, sort)

	if len(ret) == 0 {
		panic("no return value specified for ListByChannel")
	}

	var r0 []*domain.Video
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, domain.VideoSort) ([]*domain.Video, error)); ok {
		return rf(ctx, channelID, limit, offset, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, domain.VideoSort) []*domain.Video); ok {
		r0 = rf(ctx, channelID, limit, offset, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Video)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, domain.VideoSort) error); ok {
		r1 = rf(ctx, channelID, limit, offset, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFilepathsByChannel provides a mock function with given fields: ctx, channelID
func (_m *VideoRepository) ListFilepathsByChannel(ctx context.Context, channelID int) ([]string, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListFilepathsByChannel")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]string, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, video
func (_m *VideoRepository) Update(ctx context.Context, video *domain.Video) error {
	ret := _m.Called(ctx, video)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Video) error); ok {
		r0 = rf(ctx, video)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVideoRepository creates a new instance of VideoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVideoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VideoRepository {
	mock := &VideoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
