@startuml

package "Data Access Component" {

  interface VideoRepository {
    +GetByID(id int) Video
    +Save(video Video)
    +ListByChannel(channelID int) []Video
  }

  class PostgresVideoRepository {
    -db *sql.DB
    +GetByID(id int) Video
    +Save(video Video)
    +ListByChannel(channelID int) []Video
  }

  VideoRepository <|.. PostgresVideoRepository

  ' --- DB Entities ---
  class VideoDB {
    +id int
    +channel_id int
    +title string
    +description string
    +filepath string
    +preview_filepath string
    +created_at time.Time
  }

  class UserDB {
    +id int
    +role_id int
    +username string
    +email string
    +password_hash string
    +created_at time.Time
  }

}

PostgresVideoRepository --> VideoDB

package "Business Logic Component" {

  ' --- Interfaces ---
  interface VideoRepository {
    +GetByID(id int) Video
    +Save(video Video)
  }

  interface Cache {
    +Get(key string) any
    +Set(key string, value any)
  }

  ' --- Use Case ---
  class GetVideoUseCase {
    -repo VideoRepository
    -cache Cache

    +Execute(id int) Video
  }

  ' --- Domain Entity ---
  class Video {
    +ID int
    +ChannelID int
    +Title string
    +Description string
    +FilePath string
    +PreviewPath string
    +CreatedAt time.Time
  }

  GetVideoUseCase --> VideoRepository
  GetVideoUseCase --> Cache
  GetVideoUseCase --> Video

}

package "Transport Layer (DTO)" {

  class VideoResponse {
    +id int
    +title string
    +description string
    +preview_url string
    +created_at string
  }

  class UploadVideoRequest {
    +title string
    +description string
  }

}



VideoDB --> Video : mapping
Video --> VideoResponse : mapping

@enduml