REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM PUBLIC;

CREATE ROLE guest;
CREATE ROLE user;
CREATE ROLE moderator;
CREATE ROLE admin;

GRANT USAGE ON SCHEMA public TO guest, user, moderator, admin;

GRANT SELECT, INSERT ON TABLE users TO guest;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO guest;

GRANT SELECT ON TABLE roles TO user;
GRANT SELECT, UPDATE ON TABLE users TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE channels TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE videos TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE playlists TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE playlist_items TO user;
GRANT SELECT, INSERT ON TABLE viewings TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE comments TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE video_ratings TO user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE comment_ratings TO user;
GRANT SELECT, INSERT, DELETE ON TABLE subscriptions TO user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO user;

GRANT user TO moderator;
GRANT DELETE ON TABLE videos TO moderator;
GRANT DELETE ON TABLE comments TO moderator;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;

